## Claus Dethlefsen, September 2019

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
 
discovery:
  ignore:
    - philips_hue
  
recorder:
  exclude:
    domains:
      - automation
      - media_player
    entities:
      - sun.sun
      - sensor.date
  
homeassistant:
  name: !secret name 
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Copenhagen
  auth_providers:
   - type: homeassistant
  customize: !include_dir_merge_named customize

# https://community.home-assistant.io/t/lovelace-gen-add-abilities-to-ui-lovelace-yaml/130328
lovelace_gen:

lovelace:
  mode: yaml

config:
  
frontend:
  themes: !include_dir_merge_named themes

ios:

mobile_app:

input_boolean:
  first_run:
  first_run_eve:    

# read this:
# https://community.home-assistant.io/t/updating-duckdns-domain-failed/135623
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Text to speech
tts:
  - platform: google_translate
    language: 'da'

ifttt:
  key: !secret ifttt_key

#scene:
#  platform: hunterdouglas_powerview
#  address: 192.168.0.95

  
## --------------------------------------------------
## APPLE TV
## https://www.home-assistant.io/components/apple_tv/

apple_tv:
  - host: !secret apple_tv_ip
    login_id: !secret apple_tv_login_id
    name: Stue
    start_off: true
    credentials: !secret apple_tv_credentials

  
## --------------------------------------------------
## NETATMO
## https://www.home-assistant.io/components/netatmo/

netatmo:
  client_id: !secret netatmo_api_key
  client_secret: !secret netatmo_secret_key 

## --------------------------------------------------
## gogogate2
## https://www.home-assistant.io/components/gogogate2/

cover:
  - platform: gogogate2
    username: !secret gogogate_username 
    password: !secret gogogate_password
    ip_address: !secret gogogate_ip
#  - platform: hd_powerview
#    host: !secret powerview_ip

## --------------------------------------------------
## FOSCAM
## https://www.home-assistant.io/components/foscam/
camera:
  - platform: foscam
    ip: !secret foscam_ip
    port: !secret foscam_port
    username: !secret foscam_username
    password: !secret foscam_password

# Example configuration.yaml entry
#switch:
#  - platform: hikvisioncam
#    name: sommerhus
#    host: !secret sommerhus_ip
#    username: !secret sommerhus_username
#    password: !secret sommerhus_password
    
## --------------------------------------------------
## Denon AVR X2300W
## https://www.home-assistant.io/components/denonavr/

media_player:
  - platform: denonavr
    host: !secret denon_ip
    show_all_sources: True
  - platform: plex
    show_all_controls: false
    use_episode_art: true
    remove_unavailable_clients: true
    client_remove_interval: 600

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret 
  track_new_calendar: false

# Example configuration.yaml entry
garbage_collection: !include include/garbage/garbage.yaml


timer:
  indkorsel:
    duration: '00:10:00'

## hue "advanced sensors" to control dimmer swithces etc. (HACS)

remote:
  - platform: hueremote
    
#######################################################################################
# Speedtest.Net
#
# https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  scan_interval:
    minutes: 20
  monitored_conditions:
    - ping
    - download
    - upload
#######################################################################################




sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  default_class: light  

# Example configuration.yaml entry
#spotify:
#  client_id: !secret spotify_id
#  client_secret: !secret spotify_secret
  
#######################################################################################
# Allows connection of multiple device tracer entities to a single person
# 
# https://www.home-assistant.io/components/person/
#person: !include_dir_merge_list people/
#######################################################################################

#######################################################################################
# Zones allow you to specify certain regions on earth (for now).
#
# https://www.home-assistant.io/components/zone/
#
zone: !include customize/zones.yaml
#######################################################################################





weather:
  - platform: darksky
    api_key: ca823efa102eff940edf02026fd97053
    mode: daily
  
group: !include_dir_merge_named include/groups/
sensor: !include_dir_merge_list include/sensors/
automation: !include_dir_merge_list include/automations/
binary_sensor: !include_dir_merge_list include/binary_sensors/
device_tracker: !include include/device_trackers.yaml
input_datetime: !include_dir_merge_named include/input/datetime/
input_number: !include_dir_merge_named include/input/number/
input_select: !include_dir_merge_named include/input/select/
light: !include_dir_merge_list include/lights/
panel_iframe: !include_dir_merge_named include/panels/
script: !include_dir_merge_named include/scripts/
shell_command: !include_dir_merge_named include/shell_commands/
#switch: !include_dir_merge_list include/switches/



# PYTHON
python_script:

# HP PRINTER
#hpprinter:
#  devices:
#    - host: 192.168.0.41
#      name: HP 081A4C


# Example configuration.yaml entry
#scene:
#  - platform: hunterdouglas_powerview
#    address: 192.168.0.95


scene 2: !include scenes.yaml

