## Claus Dethlefsen, September 2019

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name 
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  auth_providers:
   - type: homeassistant

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Text to speech
tts:
  - platform: google_translate


binary_sensor:
  - platform: workday
    country: DK
  - platform: rest
    name: "Stue Motion Sensor"
    resource: !secret stue_url
    device_class: motion
    scan_interval: 5
    value_template: >-
      {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
        {{ true }}
      {%- else -%}
        {{ false }}
      {%- endif -%}

device_tracker:
  - platform: tile
    username: !secret tile_username 
    password: !secret tile_password

ifttt:
  key: !secret ifttt_key

## --------------------------------------------------
## NETATMO
## https://www.home-assistant.io/components/netatmo/

netatmo:
  api_key: !secret netatmo_api_key 
  secret_key: !secret netatmo_secret_key 
  username: !secret netatmo_username 
  password: !secret netatmo_password 

## --------------------------------------------------
## gogogate2
## https://www.home-assistant.io/components/gogogate2/

cover:
  - platform: gogogate2
    username: !secret gogogate_username 
    password: !secret gogogate_password
    ip_address: !secret gogogate_ip


    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
