
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: !secret name 
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Copenhagen
  auth_providers:
   - type: homeassistant
#  customize: !include_dir_merge_named customize

# https://community.home-assistant.io/t/lovelace-gen-add-abilities-to-ui-lovelace-yaml/130328

lovelace:
  mode: yaml

config:
  
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

scene:
  platform: hunterdouglas_powerview
  address: !secret powerview_ip  


#scene:
#  - platform: hunterdouglas_powerview
#    address: !secret powerview_ip  

