## Claus Dethlefsen, September 2019

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: !secret name 
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Copenhagen
  auth_providers:
   - type: homeassistant
  customize: !include_dir_merge_named customize

frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom-icons_v01.html

ios:

input_boolean:
  first_run:
      
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Text to speech
tts:
  - platform: google_translate
    language: 'da'

binary_sensor:
  - platform: workday
    country: DK
  - platform: rest
    name: "Stue Motion Sensor"
    resource: !secret stue_url
    device_class: motion
    scan_interval: 5
    value_template: >-
      {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
        {{ true }}
      {%- else -%}
        {{ false }}
      {%- endif -%}

device_tracker:
  - platform: tile
    username: !secret tile_username 
    password: !secret tile_password

ifttt:
  key: !secret ifttt_key

## --------------------------------------------------
## APPLE TV
## https://www.home-assistant.io/components/apple_tv/

#apple_tv:
#  - host: !secret apple_tv_ip
#    login_id: !secret apple_tv_login_id
#    name: Stue
#    start_off: true
#    credentials: !secret apple_tv_credentials

  
## --------------------------------------------------
## NETATMO
## https://www.home-assistant.io/components/netatmo/

netatmo:
#  api_key: !secret netatmo_api_key 
#  secret_key: !secret netatmo_secret_key 
#  username: !secret netatmo_username 
#  password: !secret netatmo_password
  client_id: !secret netatmo_api_key
  client_secret: !secret netatmo_secret_key 

## --------------------------------------------------
## gogogate2
## https://www.home-assistant.io/components/gogogate2/

cover:
  - platform: gogogate2
    username: !secret gogogate_username 
    password: !secret gogogate_password
    ip_address: !secret gogogate_ip

## --------------------------------------------------
## FOSCAM
## https://www.home-assistant.io/components/foscam/
camera:
  - platform: foscam
    ip: !secret foscam_ip
    port: !secret foscam_port
    username: !secret foscam_username
    password: !secret foscam_password

## --------------------------------------------------
## Denon AVR X2300W
## https://www.home-assistant.io/components/denonavr/

media_player:
  - platform: denonavr
    host: !secret denon_ip
    show_all_sources: True
  - platform: plex
    show_all_controls: false
    use_episode_art: true
    remove_unavailable_clients: true
    client_remove_interval: 600


google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret 
  track_new_calendar: false

#######################################################################################
# Speedtest.Net
#
# https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  scan_interval:
    minutes: 20
  monitored_conditions:
    - ping
    - download
    - upload
#######################################################################################


  
#scene:
#  platform: hunterdouglas_powerview
#  address: !secret powerview_ip

#######################################################################################
# Allows connection of multiple device tracer entities to a single person
# 
# https://www.home-assistant.io/components/person/
#person: !include_dir_merge_list people/
#######################################################################################

#######################################################################################
# Zones allow you to specify certain regions on earth (for now).
#
# https://www.home-assistant.io/components/zone/
#
zone: !include customize/zones.yaml
#######################################################################################


group: !include groups.yaml
sensor: !include sensors.yaml
automation: !include automations.yaml
script: !include scripts.yaml


scene: !include scenes.yaml

lovelace:
  mode: yaml
