# lovelace_gen


custom_header:
  compact_mode: true

title: anneclaus
resources: !include_dir_merge_list include/resources/

views:
  - !include views/main.yaml
  - !include views/rooms.yaml
#  - !include views/movies.yaml
#  - !include views/light.yaml
  - !include views/indoor.yaml
  - !include views/weather.yaml    
  - !include views/network.yaml
#  - !include views/system.yaml
  

