title: anneclaus
views:
  - badges:
      - person.claus_dethlefsen
      - person.anne_schusler_dethlefsen
      - person.andreas_schusler_dethlefsen
      - person.daniel_schusler_dethlefsen
      - sensor.gang_sensor_temperature
      - sensor.sensor.netatmo_noergaardsvej_udenfor_temperature
    cards:
      - entities:
          - entity: light.claus
          - entity: light.anne
        show_header_toggle: true
        title: Soveværelse
        type: entities
      - entities:
          - entity: cover.anne
        title: Garage
        type: entities
  - icon: mdi:home-assistant
    title: Udenfor
    cards:
      - type: entities
        title: Example
        entities:
        - light.garage
