# lovelace_gen

custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user: 'Andreas Schüsler Dethlefsen'
      config:
        show_tabs:
          - 5
    - conditions:
        user: 'Daniel Schüsler Dethlefsen'
      config:
        show_tabs:
          - 6
title: anneclaus


light_profiles:
  bright: '0.457,0.408,254'
  dimmed: '0.457,0.408,77'
  nightlight: '0.509,0.411,1'


views:
  - !include views/main.yaml
  - !include views/rooms.yaml
#  - !include views/movies.yaml
#  - !include views/light.yaml
  - !include views/indoor.yaml
  - !include views/weather.yaml    
  - !include views/network.yaml
  - !include views/andreas.yaml  
  - !include views/daniel.yaml
  - !include views/video.yaml
  - !include views/sonos.yaml
  - !include views/plex.yaml      
  - !include views/rejse.yaml
  - !include views/workout.yaml
  - !include views/el.yaml  
  - !include views/battery.yaml  
  

