title: anneclaus
resources:
  - url: /local/mini-media-player-bundle.js?v=1.6.0
    type: module
  - url: /local/atomic_calendar.js
    type: module
views:
  - title: Overblik
    cards:
      - entities:
          - entity: light.claus
          - entity: light.anne
        show_header_toggle: true
        title: Soveværelse
        type: entities
      - entities:
          - entity: cover.anne
        title: Garage
        show_header_toggle: false
        type: entities
  - icon: mdi:home-assistant
    title: Udenfor
    cards:
      - type: entities
        title: Example
        entities:
        - light.garage
