title: anneclaus
resources:
  - url: /local/mini-media-player-bundle.js?v=1.6.0
    type: module
  - url: /local/atomic_calendar.js
    type: module
views:
  - title: Overblik
    cards:
      - entities:
          - entity: light.claus
          - entity: light.anne
        show_header_toggle: true
        title: Soveværelse
        type: entities
      - entities:
          - entity: cover.anne
        title: Garage
        show_header_toggle: false
        type: entities
      - entities:
          - entity: light.bamse
          - entity: light.stue
        title: Lys
        type: entities
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.kokken
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.bad
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.kontor
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.stue
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.alrum
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.andreas
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.daniel
            group: true
            hide:
              controls: true
      - entities:
          - entity: sensor.netatmo_noergaardsvej_indenfor_co2
          - entity: sensor.netatmo_noergaardsvej_sovevaerelse_co2
          - entity: sensor.netatmo_noergaardsvej_stue_co2
        type: entities
      - entities:
          - entity: person.andreas_schusler_dethlefsen
          - entity: person.daniel_schusler_dethlefsen
          - entity: person.anne_schusler_dethlefsen
          - entity: person.claus_dethlefsen
        type: glance
      - entities:
          - entity: binary_sensor.indkorsel_sensor_motion
          - entity: binary_sensor.stue_motion_sensor
          - entity: binary_sensor.forgang_sensor_motion
          - entity: binary_sensor.gang_sensor_motion
          - entity: binary_sensor.garage_sensor_motion
        type: entities
      - entities:
          - entity: calendar.madplan
        title: "Madplan"
        type: "custom:atomic-calendar"
  - icon: mdi:home-assistant
    title: Udenfor
    cards:
      - type: entities
        title: Example
        entities:
        - light.garage
