title: anneclaus
resources:
  - url: /local/mini-media-player-bundle.js?v=1.6.0
    type: module
  - url: /local/atomic_calendar.js
    type: module
views:
  - title: Overblik
    cards:
      - entities:
          - entity: light.claus
          - entity: light.anne
        show_header_toggle: true
        title: Soveværelse
        type: entities
      - entities:
          - entity: cover.anne
        title: Garage
        show_header_toggle: false
        type: entities
      - type: "custom:atomic-calendar"
        title: "Madplan"
        showProgressBar: false
        showCurrentEventLine: false
        maxDaysToShow: 14
        dayWrapperLineColor: white
        titleSize: 110
        showMonth: true
        locationIconColor: '#f44242'
        locationlinkColor: '#B58E31'
        entities:
          - calendar.madplan
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.kokken
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.bad
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.kontor
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.stue
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.alrum
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.andreas
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.daniel
            group: true
            hide:
              controls: true
  - icon: mdi:home-assistant
    title: Udenfor
    cards:
      - type: entities
        title: Example
        entities:
        - light.garage
