title: anneclaus
resources:
  - url: /local/mini-media-player-bundle.js?v=1.4.1
    type: module
  - url: /local/atomic_calendar.js
    type: module
views:
  - badges:
      - person.claus_dethlefsen
      - person.anne_schusler_dethlefsen
      - person.andreas_schusler_dethlefsen
      - person.daniel_schusler_dethlefsen
      - sensor.gang_sensor_temperature
      - sensor.sensor.netatmo_noergaardsvej_udenfor_temperature
    cards:
      - entities:
          - entity: light.claus
          - entity: light.anne
        show_header_toggle: true
        title: Soveværelse
        type: entities
      - entities:
          - entity: cover.anne
        title: Garage
        type: entities
      - entities:
          - entity: light.andreas_2
          - entity: light.bamse
          - entity: light.daniel_2
          - entity: light.sov_1
          - entity: light.sov_2
          - entity: light.gang_nord
          - entity: light.gang_syd
          - entity: light.forgang_2
          - entity: light.stue_2
          - entity: light.stol
          - entity: light.indkoersel_plug
          - entity: light.garage_2
        title: Lys
        type: entities
      - entities:
          - sensor.netatmo_noergaardsvej_indenfor_co2
          - sensor.netatmo_noergaardsvej_stue_co2
          - sensor.netatmo_noergaardsvej_sovevaerelse_co2
          - sensor.netatmo_noergaardsvej_indenfor_humidity
          - sensor.netatmo_noergaardsvej_indenfor_temperature
          - sensor.netatmo_noergaardsvej_regnmaaler_rain
          - sensor.netatmo_noergaardsvej_regnmaaler_sum_rain_1
          - sensor.netatmo_noergaardsvej_regnmaaler_sum_rain_24
          - sensor.netatmo_noergaardsvej_udenfor_humidity
          - sensor.netatmo_noergaardsvej_udenfor_temperature
        type: entities
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.multiroom_player
            group: true
            source: icon
            info: short
            hide:
              volume: true
              power: true
          - type: custom:mini-media-player
            entity: media_player.kokken
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.bad
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.kontor
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.stue
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.alrum
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.andreas
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.daniel
            group: true
            hide:
              controls: true
      - type: "custom:atomic-calendar"
        title: "Madplan"
        showProgressBar: false
        showCurrentEventLine: false
        maxDaysToShow: 14
        dayWrapperLineColor: white
        titleSize: 110
        showMonth: true
        locationIconColor: '#f44242'
        locationlinkColor: '#B58E31'
        entities:
          - calendar.madplan
      - entity: weather.anneclaus
        type: weather-forecast
      - entities:
          - entity: camera.foscam_camera
        theme: Backend-selected
        type: entities
#      - entities:
#          - scene.34900
#          - scene.8770
#          - scene.23044
#          - scene.39601
#        title: Gardiner
#        type: entities
      - entities:
          - entity: person.andreas_schusler_dethlefsen
          - entity: person.daniel_schusler_dethlefsen
          - entity: person.anne_schusler_dethlefsen
          - entity: person.claus_dethlefsen
        type: glance
      - entities:
          - sensor.andreas_switch
          - sensor.daniel_switch
          - sensor.sovevaerelse_switch
          - sensor.stue_switch
          - sensor.stue_switch_2
        type: glance
      - entities:
          - media_player.denon_avr_x2300w
          - media_player.dagligstue
          - media_player.tv_andreas
          - media_player.tv_daniel
          - media_player.tv_stue
        type: glance
      - entities:
          - entity: binary_sensor.indkorsel_motion_sensor
          - entity: binary_sensor.stue_motion_sensor
          - entity: binary_sensor.forgang_sensor_motion
          - entity: binary_sensor.gang_motion_sensor
          - entity: binary_sensor.garage_motion_sensor
        type: entities
      - entities:
          - entity: sensor.launch_window
          - entity: sensor.next_launch
          - entity: sensor.moon
          - entity: binary_sensor.iss
        type: entities
    path: default_view
    title: Home
  - icon: mdi:home-assistant
    title: Udenfor
    cards:
      - type: entities
        title: Example
        entities:
        - light.garage
