  - alias: "Receiver On when Sonos plays in stue"
    trigger:
      - platform: state 
        entity_id: media_player.stue
        from: 'paused'
        to: 'playing'
    action:
      - service: media_player.turn_on
        entity_id: media_player.denon_avr_x2300w
      - delay: '00:00:10'
      - service: media_player.select_source
        data:
          entity_id: media_player.denon_avr_x2300w
          source: Sonos
      - service: media_player.volume_set
        data:
          entity_id: media_player.denon_avr_x2300w
          volume_level: 0.50
  - alias: "Receiver Off when Sonos stops playing in stue"
    trigger:
      - platform: state 
        entity_id: media_player.stue
        from: 'playing'
        to: 'paused'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.denon_avr_x2300w
          source: TV Audio
      - service: media_player.volume_set
        data:
          entity_id: media_player.denon_avr_x2300w
          volume_level: 0.40
      - service: media_player.turn_off
        entity_id: media_player.denon_avr_x2300w

  - alias: 'Godmorgen start igen'
    trigger:
      platform: sun
      event: sunset
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.first_run

  - alias: 'Godmorgen'
    trigger: 
      platform: state
      entity_id: binary_sensor.stue_motion_sensor
      to: 'on'
    condition:
      - condition: time
        after: '06:00:00'
        before: '10:00:00'
      - condition: state
        entity_id: input_boolean.first_run
        state: 'off'
    action:
#      - service: scene.turn_on
#        entity_id: scene.34900
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.first_run
