  - alias: 'Godmorgen start igen'
    trigger:
      platform: sun
      event: sunset
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.first_run

  - alias: 'Godmorgen'
    trigger: 
      platform: state
      entity_id: binary_sensor.stue_motion_sensor
      to: 'on'
    condition:
      - condition: time
        after: '06:00:00'
        before: '10:00:00'
      - condition: state
        entity_id: input_boolean.first_run
        state: 'off'
    action:
#      - service: scene.turn_on
#        entity_id: scene.34900
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.first_run
