- platform: group
  name: Indendørslamper
  entities:
    - light.andreas
    - light.daniels_varelse
    - light.raket
    - light.stol    
    - light.stue
    - light.sovevaerelse
    - light.gang
    - light.forgang
    - light.sonoff_10006a2cdd

- platform: group
  name: livingroom
  entities:
    - light.raket
    - light.stol    
    - light.stue

- platform: group
  name: kids
  entities:
    - light.andreas
    - light.daniel
    - light.bamse

- platform: group
  name: bed
  entities:
    - light.anne
    - light.claus
    - light.bamse
    
- platform: group
  name: bedroom
  entities:
    - light.anne
    - light.claus
    - light.sovevaerelse_loft
    
- platform: group
  name: Indkørsel
  entities:
    - light.indkoersel_plug
    - light.fordoer
    
- platform: group
  name: Udendørslamper
  entities:
    - light.garage
    - light.indkoersel_plug
    - light.fordoer    
    - light.sonoff_100069a6cc
    - light.sonoff_1000a76e41    
#    - switch.sonoff_100069a6cc
#    - switch.sonoff_10006a2cdd
#    - switch.sonoff_1000a76e41

- platform: group
  name: Alle lys
  entities:
    - light.indendorslamper
    - light.udendorslamper

  
  
